# Setup
title: Leverage Points
#tagline: The Jekyll Butler
url: https://leveragepoints.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed


pages_list:       
  # About: '/about'
  # Newsletter: 'https://leveragepoints.substack.com/'

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Paulo Cunha
  url: 
  email: 

# Custom vars
version: 3.0.0
