# Setup
title: Leverage Points
#tagline: The Jekyll Butler
url: https://leveragepoints.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag



# Delta: Make permalinks work for pages source: https://stackoverflow.com/questions/62104684/managing-jekyll-pages-in-folders-on-github-pages
include:
  - _pages

defaults:
  - scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: /:basename/ # make URL of pages in the folder _pages as on the root.


# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Paulo Cunha
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom vars
version: 3.0.0
